# Default values for thunderhub-helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: docker.io/apotdevin/thunderhub
  pullPolicy: IfNotPresent
  tag: "base-v0.12.21"

podAnnotations: {}

livenessProbe:
  enabled: false
  path: "/thub/login"

readinessProbe:
  enabled: false
  path: "/thub/login"

secrets:
  certificates:
    path: "/data/.lnd"
    enable: true
    secretName: thunderhub-connection-secrets
  env:
    enable: true
    secretName: secrets-env
  account_config:
    enable: false
    secretName: config-secret
    path: /data/config_secret

service:
  type: ClusterIP
  port: 3000

network: 'testnet'

serverUrl: {}

nodeSelector: {}

tolerations: []

affinity: {}
